### PART-1 Feature Engineering
## Task-1:-Creating new Features

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [6]:
train=pd.read_csv('train.csv')
train.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [7]:
test=pd.read_csv('test.csv')
test.head()

   PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

In [8]:
train.shape

(891, 12)

In [9]:
test.shape

(418, 11)

In [10]:
df=pd.concat([train,test])
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1       0.0       3  ...   7.2500   NaN         S
1            2       1.0       1  ...  71.2833   C85         C
2            3       1.0       3  ...   7.9250   NaN         S
3            4       1.0       1  ...  53.1000  C123         S
4            5       0.0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [11]:
df.sample

<bound method NDFrame.sample of      PassengerId  Survived  Pclass  ...      Fare Cabin  Embarked
0              1       0.0       3  ...    7.2500   NaN         S
1              2       1.0       1  ...   71.2833   C85         C
2              3       1.0       3  ...    7.9250   NaN         S
3              4       1.0       1  ...   53.1000  C123         S
4              5       0.0       3  ...    8.0500   NaN         S
..           ...       ...     ...  ...       ...   ...       ...
413         1305       NaN       3  ...    8.0500   NaN         S
414         1306       NaN       1  ...  108.9000  C105         C
415         1307       NaN       3  ...    7.2500   NaN         S
416         1308       NaN       3  ...    8.0500   NaN         S
417         1309       NaN       3  ...   22.3583   NaN         C

[1309 rows x 12 columns]>

In [12]:
df.sample(5)

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
65           957       NaN       2  ...  21.0000   NaN         S
84           976       NaN       2  ...  10.7083   NaN         Q
610          611       0.0       3  ...  31.2750   NaN         S
45            46       0.0       3  ...   8.0500   NaN         S
333         1225       NaN       3  ...  15.7417   NaN         C

[5 rows x 12 columns]

## adding new column naming Family Size

In [13]:
df['Family Size']=df['SibSp']+df['Parch']+1
df.head()

   PassengerId  Survived  Pclass  ... Cabin Embarked  Family Size
0            1       0.0       3  ...   NaN        S            2
1            2       1.0       1  ...   C85        C            2
2            3       1.0       3  ...   NaN        S            1
3            4       1.0       1  ...  C123        S            2
4            5       0.0       3  ...   NaN        S            1

[5 rows x 13 columns]

# Now generating the function for adding new column Family type.

In [14]:
def fam_type(num):
    if num>=1 and num<=3:
        return 'small Family'
    elif num>=3 and num<=5:
        return 'medium Family'
    else:
        return 'large Family'

In [15]:
df['Family Type']=df['Family Size'].apply(fam_type)
df.head()

   PassengerId  Survived  Pclass  ... Embarked Family Size   Family Type
0            1       0.0       3  ...        S           2  small Family
1            2       1.0       1  ...        C           2  small Family
2            3       1.0       3  ...        S           1  small Family
3            4       1.0       1  ...        S           2  small Family
4            5       0.0       3  ...        S           1  small Family

[5 rows x 14 columns]

In [16]:
df['Family Type'].value_counts()

Family Type
small Family     1184
medium Family      65
large Family       60
Name: count, dtype: int64

In [17]:
df[df['SibSp']==5]

     PassengerId  Survived  Pclass  ... Embarked Family Size   Family Type
59            60       0.0       3  ...        S           8  large Family
71            72       0.0       3  ...        S           8  large Family
386          387       0.0       3  ...        S           8  large Family
480          481       0.0       3  ...        S           8  large Family
683          684       0.0       3  ...        S           8  large Family
140         1032       NaN       3  ...        S           8  large Family

[6 rows x 14 columns]

In [18]:
df[df['Ticket']=='CA 2144']

     PassengerId  Survived  Pclass  ... Embarked Family Size   Family Type
59            60       0.0       3  ...        S           8  large Family
71            72       0.0       3  ...        S           8  large Family
386          387       0.0       3  ...        S           8  large Family
480          481       0.0       3  ...        S           8  large Family
678          679       0.0       3  ...        S           8  large Family
683          684       0.0       3  ...        S           8  large Family
139         1031       NaN       3  ...        S           8  large Family
140         1032       NaN       3  ...        S           8  large Family

[8 rows x 14 columns]

In [19]:
df['Individual Fare']=(df['Fare']/df['Family Size'])
df.head()

   PassengerId  Survived  Pclass  ... Family Size   Family Type  Individual Fare
0            1       0.0       3  ...           2  small Family          3.62500
1            2       1.0       1  ...           2  small Family         35.64165
2            3       1.0       3  ...           1  small Family          7.92500
3            4       1.0       1  ...           2  small Family         26.55000
4            5       0.0       3  ...           1  small Family          8.05000

[5 rows x 15 columns]

In [20]:
df[df['Ticket']=='CA 2144'][['Name','Family Size','Fare','Individual Fare']]

                                        Name  ...  Individual Fare
59        Goodwin, Master. William Frederick  ...           5.8625
71                Goodwin, Miss. Lillian Amy  ...           5.8625
386          Goodwin, Master. Sidney Leonard  ...           5.8625
480           Goodwin, Master. Harold Victor  ...           5.8625
678  Goodwin, Mrs. Frederick (Augusta Tyler)  ...           5.8625
683              Goodwin, Mr. Charles Edward  ...           5.8625
139           Goodwin, Mr. Charles Frederick  ...           5.8625
140              Goodwin, Miss. Jessie Allis  ...           5.8625

[8 rows x 4 columns]

In [21]:
df['Name Prefix']=df['Name'].str.split(',').str[1].str.split('.').str[0].str.strip()

In [22]:
df['Name Prefix'].value_counts()

Name Prefix
Mr              757
Miss            260
Mrs             197
Master           61
Rev               8
Dr                8
Col               4
Ms                2
Major             2
Mlle              2
Don               1
Mme               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Dona              1
Name: count, dtype: int64

## Task:-2 Handling Date & Text Features
- There is no date column in this data set, so i have skipped this
- but i have tried to create a new features text_length, and word_count

In [23]:
df['Text_length']=df['Name'].str.len()
df['word_count']=df['Name'].str.split().str.len()

In [24]:
df.head()

   PassengerId  Survived  Pclass  ... Name Prefix Text_length  word_count
0            1       0.0       3  ...          Mr          23           4
1            2       1.0       1  ...         Mrs          51           7
2            3       1.0       3  ...        Miss          22           3
3            4       1.0       1  ...         Mrs          44           7
4            5       0.0       3  ...          Mr          24           4

[5 rows x 18 columns]

### PART-2 Feature Encoding
# Task:-3 OnehotEncoder

In [25]:
bank=pd.read_csv('Bank_Marketing_Original_Data.csv')

In [26]:
bank.head()

   Age           Job  Marital  Education  ... Pdays  Previous poutcome TARGET
0   58    management  married   tertiary  ...    -1         0  unknown     no
1   44    technician   single  secondary  ...    -1         0  unknown     no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown     no
3   47   blue-collar  married    unknown  ...    -1         0  unknown     no
4   33       unknown   single    unknown  ...    -1         0  unknown     no

[5 rows x 17 columns]

In [262]:
nominal_data=bank[['Job', 'Marital', 'Education', 'Default', 'Housing', 'Loan', 'contact',  'Month', 'poutcome']]

In [263]:
nominal_data

                Job   Marital  Education Default  ... Loan    contact Month poutcome
0        management   married   tertiary      no  ...   no    unknown   may  unknown
1        technician    single  secondary      no  ...   no    unknown   may  unknown
2      entrepreneur   married  secondary      no  ...  yes    unknown   may  unknown
3       blue-collar   married    unknown      no  ...   no    unknown   may  unknown
4           unknown    single    unknown      no  ...   no    unknown   may  unknown
...             ...       ...        ...     ...  ...  ...        ...   ...      ...
45206    technician   married   tertiary      no  ...   no   cellular   nov  unknown
45207       retired  divorced    primary      no  ...   no   cellular   nov  unknown
45208       retired   married  secondary      no  ...   no   cellular   nov  success
45209   blue-collar   married  secondary      no  ...   no  telephone   nov  unknown
45210  entrepreneur   married  secondary      no  ...   no   cellular   nov    other

[45211 rows x 9 columns]

In [264]:
bank['poutcome'].value_counts()

poutcome
unknown    36959
failure     4901
other       1840
success     1511
Name: count, dtype: int64

In [265]:
bank['Marital'].value_counts()

Marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [266]:
from pandas import get_dummies
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [267]:
nominal_data = ohe.fit_transform(nominal_data)

In [268]:
nominal_data

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 1., 0., 0.]], shape=(45211, 44))

## Task:-4 column Transformer

In [269]:
bank.head()

   Age           Job  Marital  Education  ... Pdays  Previous poutcome TARGET
0   58    management  married   tertiary  ...    -1         0  unknown     no
1   44    technician   single  secondary  ...    -1         0  unknown     no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown     no
3   47   blue-collar  married    unknown  ...    -1         0  unknown     no
4   33       unknown   single    unknown  ...    -1         0  unknown     no

[5 rows x 17 columns]

# Transformers----> ordinalencoder,onhotencoder,simpleimputer

In [270]:
bank.isnull().sum()

Age          0
Job          0
Marital      0
Education    0
Default      0
Balance      0
Housing      0
Loan         0
contact      0
Day          0
Month        0
Duration     0
Campaign     0
Pdays        0
Previous     0
poutcome     0
TARGET       0
dtype: int64

In [271]:

from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

In [272]:
from math import remainder


transformer=ColumnTransformer(transformers=[('tr1',OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']]),['Education']),('tr2',OneHotEncoder(),['Job','Marital','Education','Default','Housing','Loan','contact','Month','poutcome'])],remainder='passthrough')

In [273]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tr1',
                                 OrdinalEncoder(categories=[['unknown',
                                                             'primary',
                                                             'secondary',
                                                             'tertiary']]),
                                 ['Education']),
                                ('tr2', OneHotEncoder(),
                                 ['Job', 'Marital', 'Education', 'Default',
                                  'Housing', 'Loan', 'contact', 'Month',
                                  'poutcome'])])

In [274]:
x=bank.iloc[:,:-1]
x

       Age           Job   Marital  ... Pdays Previous  poutcome
0       58    management   married  ...    -1        0   unknown
1       44    technician    single  ...    -1        0   unknown
2       33  entrepreneur   married  ...    -1        0   unknown
3       47   blue-collar   married  ...    -1        0   unknown
4       33       unknown    single  ...    -1        0   unknown
...    ...           ...       ...  ...   ...      ...       ...
45206   51    technician   married  ...    -1        0   unknown
45207   71       retired  divorced  ...    -1        0   unknown
45208   72       retired   married  ...   184        3   success
45209   57   blue-collar   married  ...    -1        0   unknown
45210   37  entrepreneur   married  ...   188       11     other

[45211 rows x 16 columns]

In [275]:
y=bank['TARGET']
y

0         no
1         no
2         no
3         no
4         no
        ...
45206    yes
45207    yes
45208    yes
45209     no
45210     no
Name: TARGET, Length: 45211, dtype: str

In [276]:
X=transformer.fit_transform(x)

In [277]:
X

array([[  3.,   0.,   0., ...,   1.,  -1.,   0.],
       [  2.,   0.,   0., ...,   1.,  -1.,   0.],
       [  2.,   0.,   0., ...,   1.,  -1.,   0.],
       ...,
       [  2.,   0.,   0., ...,   5., 184.,   3.],
       [  2.,   0.,   1., ...,   4.,  -1.,   0.],
       [  2.,   0.,   0., ...,   2., 188.,  11.]], shape=(45211, 52))

In [278]:
le=LabelEncoder()

In [279]:
Y=le.fit_transform(y)

In [280]:
Y

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))

## PART 3:- Feature scaling
# Task5:-Standardization(StandardScaler)

In [281]:
bank.head()

   Age           Job  Marital  Education  ... Pdays  Previous poutcome TARGET
0   58    management  married   tertiary  ...    -1         0  unknown     no
1   44    technician   single  secondary  ...    -1         0  unknown     no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown     no
3   47   blue-collar  married    unknown  ...    -1         0  unknown     no
4   33       unknown   single    unknown  ...    -1         0  unknown     no

[5 rows x 17 columns]

# 1.Application

In [282]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()

In [283]:
numerical_column=bank[['Age', 'Balance', 'Day', 'Duration', 'Campaign', 'Pdays', 'Previous']]

In [284]:
SS=ss.fit_transform(numerical_column)

In [285]:
numerical_column

       Age  Balance  Day  Duration  Campaign  Pdays  Previous
0       58     2143    5       261         1     -1         0
1       44       29    5       151         1     -1         0
2       33        2    5        76         1     -1         0
3       47     1506    5        92         1     -1         0
4       33        1    5       198         1     -1         0
...    ...      ...  ...       ...       ...    ...       ...
45206   51      825   17       977         3     -1         0
45207   71     1729   17       456         2     -1         0
45208   72     5715   17      1127         5    184         3
45209   57      668   17       508         4     -1         0
45210   37     2971   17       361         2    188        11

[45211 rows x 7 columns]

# 2. Explaination
- It is the type of feature scaling, the scaling is done to keep all of the values in a standard scale range-->for all scaled values the mean becomes 0, and standard deviation becomes 1.
- It is achived by using the formula (x-mean)/standard deviation
- Different features are in different scales.in machine learning algorithms(like-logistic Regression,KNN,SVM)are scale sensitive.
- With the standardization all features come in one scale only,and model become fair and accurate.

## Task:-6 Normalization(MinMaxScaler)

In [286]:
bank.head()

   Age           Job  Marital  Education  ... Pdays  Previous poutcome TARGET
0   58    management  married   tertiary  ...    -1         0  unknown     no
1   44    technician   single  secondary  ...    -1         0  unknown     no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown     no
3   47   blue-collar  married    unknown  ...    -1         0  unknown     no
4   33       unknown   single    unknown  ...    -1         0  unknown     no

[5 rows x 17 columns]

In [287]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()

In [288]:
numerical_column=bank[['Age', 'Balance', 'Day', 'Duration', 'Campaign', 'Pdays', 'Previous']]

In [289]:
MM=mm.fit_transform(numerical_column)

In [290]:
numerical_column

       Age  Balance  Day  Duration  Campaign  Pdays  Previous
0       58     2143    5       261         1     -1         0
1       44       29    5       151         1     -1         0
2       33        2    5        76         1     -1         0
3       47     1506    5        92         1     -1         0
4       33        1    5       198         1     -1         0
...    ...      ...  ...       ...       ...    ...       ...
45206   51      825   17       977         3     -1         0
45207   71     1729   17       456         2     -1         0
45208   72     5715   17      1127         5    184         3
45209   57      668   17       508         4     -1         0
45210   37     2971   17       361         2    188        11

[45211 rows x 7 columns]

## PART-4 Building ML Pipeline
# Task:-7 Create a Preprocessing Pipeline

In [291]:
df=pd.read_csv('Bank_Marketing_Original_Data.csv')
df.head()

   Age           Job  Marital  Education  ... Pdays  Previous poutcome TARGET
0   58    management  married   tertiary  ...    -1         0  unknown     no
1   44    technician   single  secondary  ...    -1         0  unknown     no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown     no
3   47   blue-collar  married    unknown  ...    -1         0  unknown     no
4   33       unknown   single    unknown  ...    -1         0  unknown     no

[5 rows x 17 columns]

In [338]:
Numeric_Data=['Age','Balance','Day','Duration','Campaign','Pdays','Previous']

Ordinal_Data=['Education']

# 1.create seperate pipeline

In [339]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.preprocessing import StandardScaler

In [340]:
Numeric_pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='mean')),('scaling',StandardScaler())])

In [341]:
ordinal_pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='most_frequent')),('encoding',OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']])),('scaling',StandardScaler())])

# 2.Combining using ColumnTransformer

In [342]:
from sklearn.compose import ColumnTransformer

In [343]:
features=ColumnTransformer(
    transformers=[
        ('numeric transformation', Numeric_pipeline, Numeric_Data),
        ('ordinal transformation', ordinal_pipeline, Ordinal_Data),
    ]
    
)

## Task:-8 Full Scikit-learn Pipeline

# 1.Create a complete pipline using sckit learn pipeline library:

In [344]:
df=pd.read_csv('Bank_Marketing_Original_Data.csv')
df.head()

   Age           Job  Marital  Education  ... Pdays  Previous poutcome TARGET
0   58    management  married   tertiary  ...    -1         0  unknown     no
1   44    technician   single  secondary  ...    -1         0  unknown     no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown     no
3   47   blue-collar  married    unknown  ...    -1         0  unknown     no
4   33       unknown   single    unknown  ...    -1         0  unknown     no

[5 rows x 17 columns]

In [345]:
Numeric_Data=['Age','Balance','Day','Duration','Campaign','Pdays','Previous']

Ordinal_Data=['Education']

Nominal_Data=['Job','Marital','Default','Housing','Loan','contact','Month','poutcome']

In [346]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.preprocessing import StandardScaler

# 2. Raw data---->Encoding ---->Scaling

In [347]:
Numeric_pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='mean')),('scaling',StandardScaler())])

ordinal_pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='most_frequent')),('encoding',OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']])),('scaling',StandardScaler())])

Nominal_pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='most_frequent')),('Encoding',OneHotEncoder(handle_unknown='ignore'))])

In [348]:
from sklearn.compose import ColumnTransformer

In [349]:
features=ColumnTransformer(
    transformers=[
        ('numeric transformation', Numeric_pipeline, Numeric_Data),
        ('ordinal transformation', ordinal_pipeline, Ordinal_Data),
        ('nominal transformation', Nominal_pipeline, Nominal_Data)
    ]
)

# --> Model

In [350]:
from sklearn.linear_model import LogisticRegression

In [351]:
model=Pipeline(steps=[('features',features),('classifier',LogisticRegression())])

In [352]:
model

Pipeline(steps=[('features',
                 ColumnTransformer(transformers=[('numeric transformation',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Age', 'Balance', 'Day',
                                                   'Duration', 'Campaign',
                                                   'Pdays', 'Previous']),
                                                 ('ordinal transformation',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OrdinalEncoder(catego...nown',
                                                                                               'primary',
                                                                                               'secondary',
                                                                                               'tertiary']])),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Education']),
                                                 ('nominal transformation',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('Encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Job', 'Marital', 'Default',
                                                   'Housing', 'Loan', 'contact',
                                                   'Month', 'poutcome'])])),
                ('classifier', LogisticRegression())])

# 4. Split data into train test sets

In [353]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [354]:
x=df.iloc[:,:-1]
y=df['TARGET']

In [355]:
le=LabelEncoder()
y=le.fit_transform(y)

In [356]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

# 5. Fit the pipeline on training data

In [357]:
model.fit(x_train,y_train)

Pipeline(steps=[('features',
                 ColumnTransformer(transformers=[('numeric transformation',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Age', 'Balance', 'Day',
                                                   'Duration', 'Campaign',
                                                   'Pdays', 'Previous']),
                                                 ('ordinal transformation',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OrdinalEncoder(catego...nown',
                                                                                               'primary',
                                                                                               'secondary',
                                                                                               'tertiary']])),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Education']),
                                                 ('nominal transformation',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('Encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Job', 'Marital', 'Default',
                                                   'Housing', 'Loan', 'contact',
                                                   'Month', 'poutcome'])])),
                ('classifier', LogisticRegression())])

# 6. Prediction on test data

In [358]:
y_predict=model.predict(x_test)

In [359]:
from sklearn.metrics import accuracy_score

In [360]:
accuracy_score(y_test,y_predict)

0.9018024991706293

## Task:-9 Pipeline benefits(Conceptual)
# 1.Importance of pipeline
- Pipeline make the whole machine learning process organized.they connect steps like data cleaning,feature selection, and model training into one flow.This saves time and reduces mistakes. 
- Pipeline helps to chain together multiple steps,such that output data--->Imputing----> Encoding ---->Feature Scaling.
# 2.Problem solving pipeline
- Doing the same steps again and again manually.
- Forgetting or mixing up peprocessing steps.
- Making sure training and testing dat are processed in the same way.
# 3. Difference b/w manual and pipeline based preprocessing
- MANUAL PREPROCESSING-Cleaning and transforming data step by step by self,easy to make mistakes or forget steps.
- PIPELINE PREPROCESSING- Steps are defined once in the pipeline.every time data goes through,the same process is applied automatically.its consistent and less error-prone